name: CI
on:
  - push

jobs:
  build:
    name: build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x86_64
          - armhf
          - armv7
          - aarch64
          - ppc64le
          - s390x
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.2/alpine-chroot-install \
              && echo '60c7e0b5d82e21d1a549fc9a46ba3b36688c09dc  alpine-chroot-install' | sha1sum -c \
              || exit 1
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -a ${{ matrix.arch }} -i $(pwd)
      - run: /alpine/enter-chroot apk add abuild
      - run: /alpine/enter-chroot addgroup ${USER} abuild
      - run: |
          echo "${{ secrets.ABUILD_ARCHIVE }}" | \
          base64 -d | \
          /alpine/enter-chroot -u ${USER} tar xzv -C ~/
      - run: |
          cd apk
          /alpine/enter-chroot -u ${USER} abuild -c -P /tmp/
          cd ..
      - run: mv microinit{,-${{ matrix.arch }}}
      - run: mv /alpine/tmp/microinit/${{ matrix.arch }}/microinit-*.apk microinit-${{ matrix.arch }}.apk
      - run: /alpine/destroy --remove
      - uses: actions/upload-artifact@v2
        with:
          name: microinit-${{ matrix.arch }}.apk
          path: microinit-${{ matrix.arch }}.apk
          retention-days: 5
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: microinit-${{ matrix.arch }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
